### ISSUE TITLE
Fail to send SMS request, The underlying connection was closed

### ISSUE THREAD

**Issue by kirajhpang** [Nexmo/nexmo-dotnet#110]
### Which target framework(s) of .NET can you reproduce this issue against?
4.5.2

### What operating system(s) is exhibiting this issue?
IIS, ASP NET MVC 

### Version or commit hash
v3.1.0

### Expected Behavior
SMS successful sent

### Actual Behavior
SMS fail to send, exception throw since mid of August

```
System.AggregateException
  HResult=0x80131500
  Message=One or more errors occurred.
  Source=mscorlib
  StackTrace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Nexmo.Api.Request.ApiRequest.DoRequest(String method, Uri uri, Dictionary`2 parameters, Credentials creds)
   at Nexmo.Api.SMS.Send(SMSRequest request, Credentials creds)
   at Nexmo.Api.ClientMethods.SMS.Send(SMSRequest request, Credentials creds)
   at Softinn.NexmoService.NexmoService.SendSms(NexmoViewModel nexmo) in C:\....\NexmoService.cs:line 74

Inner Exception 1:
HttpRequestException: An error occurred while sending the request.

Inner Exception 2:
WebException: The underlying connection was closed: An unexpected error occurred on a send.

Inner Exception 3:
IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.

Inner Exception 4:
SocketException: An existing connection was forcibly closed by the remote host
```

### Steps to Reproduce
```
<sample code>
nexmo.Sender = "<nexmo number>";
nexmo.Receiver = "<working mobile number>";
nexmo.Msg = "[test]" + nexmo.Msg;

var client = new Nexmo.Api.Client(creds: new Credentials("xxx", "xxxx"));
                var results = client.SMS.Send(request: new SMS.SMSRequest()
                {
                    from = nexmo.Sender,
                    text = nexmo.Msg,
                    to = nexmo.Receiver
                });
```

**Comment by leggetter** [comment]
Seems you may be hitting the TLS update we recently made. See https://github.com/Nexmo/nexmo-dotnet/issues/105#issuecomment-414913881

**Comment by kirajhpang** [comment]
🤕 
Why there is no announcement/email notification for this setting?

solve by adding this line of code

`ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;`
