### ISSUE TITLE
System.ArgumentNullException : Value cannot be null. (Parameter 'value')

### ISSUE THREAD

**Issue by bawoodruff** [Nexmo/nexmo-dotnet#185]
### General description of the issue or question
```
System.ArgumentNullException : Value cannot be null. (Parameter 'value')
   at Newtonsoft.Json.Utilities.ValidationUtils.ArgumentNotNull(Object value, String parameterName)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at Nexmo.Api.SMS.Send(SMSRequest request, Credentials creds)
   at Nexmo.Api.ClientMethods.SMS.Send(SMSRequest request, Credentials creds)
   at Cortexa.Harvana.Messaging.NexmoMessaging.<>c__DisplayClass5_0.<SendText>b__0() in /Users/bryanw/Projects/Harvana/server/Messaging.Nexmo/NexmoMessaging.cs:line 67
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Cortexa.Harvana.UnitTests.NexmoMessagingTests.SendTextShouldReturnTrue() in /Users/bryanw/Projects/Harvana/server/UnitTests/NexmoMessagingTests.cs:line 53
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_0(Object state)
```

The issue is in the SMS.Send() implementation:
```
var response = ApiRequest.DoPostRequest(ApiRequest.GetBaseUriFor(typeof(SMSResponse), "/sms/json"), request, creds);

return JsonConvert.DeserializeObject<SMSResponse>(response.JsonResponse);
```

The issue is that when the request returns an error such as a server error, bad gateway, etc. the JsonResponse is null.  The NexmoResponse result code is lost.  Given the current design of this API, I'd like to propose an override that accepts a new out parameter HttpResponseCode and returns null for the SMSResponse in these error cases.

### Which target framework(s) of .NET can you reproduce this issue against?
(Examples: .NET Core 2.0, netcoreapp1.0, .NET Framework 4.6.2, etc.)

### What operating system(s) is exhibiting this issue?
macOS, Windows

### Version or commit hash
Nexmo.Csharp.Client/4.3.0 also in ToT
 
### Expected Behavior
No exception.

### Actual Behavior
System.ArgumentNullException due to request error

### Steps to Reproduce
Modify SendAsync() in the MockedWebTest class to return an error response:

```
    return Task.FromResult(new HttpResponseMessage(HttpStatusCode.InternalServerError)
        {
            Content = new StringContent(string.Empty),
            ReasonPhrase = "Internal Server Error.",
        });
```

**Comment by slorello89** [comment]
Hi @bawoodruff 

The next major version of the SDK will set the default behavior to toss an exception with the status code and the content of the failed request.

For the moment you should be able to override the default behavior and make it throw an exception that describes the error by setting the configuration item  `appSettings:Nexmo.Api.EnsureSuccessStatusCode` to true.

Generally, when the SMS API fails it 200's and passes out an error code describing the error out in it's `status` so if you're getting a 4xx it's in all likelihood not reaching the API

**Comment by bawoodruff** [comment]
@slorello89 I pushed a change that uses an out parameter to return the HttpStatusCode.   This is how I'm addressing this locally.

I'm ran into these issues by mocking the responses (e.g. mountebank) and now using the underlying HttpClientHandler to simulate service client request responses.

**Comment by bawoodruff** [comment]
Given that you have a solution forthcoming, I'll use my current implementation until the next SDK update.
