### ISSUE TITLE
TypeInitializationException: The type initializer for 'Nexmo.Api.Configuration' threw an exception.

### ISSUE THREAD

**Issue by khaledelmahdi** [Nexmo/nexmo-dotnet#40]
Hi,

Using AspNetCore Core 2.0.0-preview2-final and Nexmo.Csharp.Client 3.0.0-pre1

My `appsettings.json`:

```
{
  "Nexmo": {
    "ApiKey": "key",
    "ApiSecret": "secret"
  }
}
```

My interface:

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Lettingbox.Services
{
    public interface ISmsSender
    {
        Task SendSmsAsync(string number, string message);
    }
}
```

My class:

```
using System;
using System.Threading.Tasks;
using Nexmo.Api;
using Microsoft.Extensions.Options;

namespace Lettingbox.Services.Sms
{
    public class SmsSender : ISmsSender
    {
        public SmsSender(IOptions<NexmoSettings> optionsAccessor)
        {
            Options = optionsAccessor.Value;
        }

        public NexmoSettings Options { get; }

        Task ISmsSender.SendSmsAsync(string number, string message)
        {
            SMS.Send(new SMS.SMSRequest
            {
                from = "Lettingbox",
                to = number,
                text = message
            }, new Nexmo.Api.Request.Credentials
            {
                ApiKey = Options.ApiKey,
                ApiSecret = Options.ApiSecret,
                
            });

            return Task.FromResult(0);
        }
    }

    public class NexmoSettings
    {
        public string ApiKey { get; set; }
        public string ApiSecret { get; set; }
    }
}
```

and finally on my `Startup.cs` under `ConfigureServices` I have:

```
services.Configure<Lettingbox.Services.Sms.NexmoSettings>(Configuration.GetSection("Nexmo"));
```

When I try to send a message I get the following errors:
```
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HL6QJGOR268V", Request id "0HL6QJGOR268V:00000001": An unhandled exception was thrown by the application.
System.TypeInitializationException: The type initializer for 'Nexmo.Api.Configuration' threw an exception. ---> System.MissingMethodException: Method not found: 'System.IServiceProvider Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(Microsoft.Extensions.DependencyInjection.IServiceCollection)'.
   at Nexmo.Api.Configuration..ctor()
   at Nexmo.Api.Configuration..cctor()
   --- End of inner exception stack trace ---
   at Nexmo.Api.Request.ApiRequest.GetBaseUriFor(Type component, String url)
   at Nexmo.Api.SMS.Send(SMSRequest request, Credentials creds)
   at Lettingbox.Services.Sms.SmsSender.Lettingbox.Services.ISmsSender.SendSmsAsync(String number, String message) in /Users/khaled/bitbucket/lettingbox/net/Services/Sms/SmsSender.cs:line 19
   at Lettingbox.Controllers.HomeController.<Index>d__2.MoveNext() in /Users/khaled/bitbucket/lettingbox/net/Controllers/HomeController.cs:line 19
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()
```

Any idea what I am doing wrong?

**Comment by smithrobs** [comment]
Hey @khaledelmahdi ! Sorry - what was the error message?

**Comment by khaledelmahdi** [comment]
Sorry, here it is:

```
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HL6QJGOR268V", Request id "0HL6QJGOR268V:00000001": An unhandled exception was thrown by the application.
System.TypeInitializationException: The type initializer for 'Nexmo.Api.Configuration' threw an exception. ---> System.MissingMethodException: Method not found: 'System.IServiceProvider Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(Microsoft.Extensions.DependencyInjection.IServiceCollection)'.
   at Nexmo.Api.Configuration..ctor()
   at Nexmo.Api.Configuration..cctor()
   --- End of inner exception stack trace ---
   at Nexmo.Api.Request.ApiRequest.GetBaseUriFor(Type component, String url)
   at Nexmo.Api.SMS.Send(SMSRequest request, Credentials creds)
   at Lettingbox.Services.Sms.SmsSender.Lettingbox.Services.ISmsSender.SendSmsAsync(String number, String message) in /Users/khaled/bitbucket/lettingbox/net/Services/Sms/SmsSender.cs:line 19
   at Lettingbox.Controllers.HomeController.<Index>d__2.MoveNext() in /Users/khaled/bitbucket/lettingbox/net/Controllers/HomeController.cs:line 19
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()
```

**Comment by smithrobs** [comment]
I could get your code to run with aspnet core 1.1.3 and the nexmo 3.0.0-pre1 library. I tried to get 2.0.0-preview2-final to cooperate with my mac environment, but ran into issues. Current thoughts:

- Since aspnet core 2 is still in preview, can you try using aspnet core 1.1.3?
- I will try to see if I can get 2.0.0-preview2 running in my Windows environment.

**Comment by khaledelmahdi** [comment]
Sadly downgrading is not an option here. I'll wait and see, hopefully you will find out what is wrong.

Thanks.

**Comment by khaledelmahdi** [comment]
After googling, it seems this error due to version deferences in dot net.

So until .net core 2 is release, and you have a version compatible with it, I'll just use this code to send SMS:

```
        Task ISmsSender.SendSmsAsync(string number, string message)
        {
            using (var client = new HttpClient())
            {
                var values = new List<KeyValuePair<string, string>>();
                values.Add(new KeyValuePair<string, string>("from", "Lettingbox"));
                values.Add(new KeyValuePair<string, string>("text", message));
                values.Add(new KeyValuePair<string, string>("to", number));
                values.Add(new KeyValuePair<string, string>("api_key", Options.ApiKey));
                values.Add(new KeyValuePair<string, string>("api_secret", Options.ApiSecret));

                var content = new FormUrlEncodedContent(values);

                client.PostAsync("https://rest.nexmo.com/sms/json", content).Wait();
            }

            return Task.FromResult(0);
        }
``` 

Thanks.

**Comment by smithrobs** [comment]
I see, yes. Thank you for bringing this to our attention. We will have to address for aspnet core 2 due to [this issue in DI](https://github.com/aspnet/DependencyInjection/issues/550). Closing this and will add a note to #37
