### ISSUE TITLE
The type initializer for 'Nexmo.Api.Configuration' threw an exception

### ISSUE THREAD

**Issue by lebanon35** [Nexmo/nexmo-dotnet#97]
Hello,

I created a Visual Basic.Net Windows Forms application to send SMS using Nexmo. It's working completely fine on the development environment, however when the executable and DLL files are moved to the live server, it gives the following error:

The type initializer for 'Nexmo.Api.Configuration' threw an exception. - Nexmo.Api -    at Nexmo.Api.Configuration.get_Instance()
   at Nexmo.Api.Request.ApiRequest.GetBaseUriFor(Type component, String url)
   at Nexmo.Api.SMS.Send(SMSRequest request, Credentials creds)

Both the dev and live machines have .Net Framework 4.6.1
Nexmo Version 3.0.1.0 was installed through Nuget Package, which downloaded many microsoft dependencies with it.

Dev machine is Microsoft Windows 10 Home
Live server is Microsoft Windows Server 2012 Standard - 64 bit

Thank you,

**Comment by lebanon35** [comment]
The issue was solved by performing a Windows Update which included some updates to .Net Frameworks.

Everything is working fine now.

Thanks,
